import db from '../lib/db'
import appConfig from '../../app-config.js'
const connection = db.getConnection(appConfig.users.database)

export const create = function(req, res, next){
    let {
        activo,
        asignacion,
        cuentanProcesos,
        cuentanProcesosObs,
        cuantosProcesosObs,
        procesoPatentado,
        procesoPatentadoObs,
        anioDesarrolloObs,
        equipoTrabajo,
        equipoTrabajoObs,
        cuantosEspecialistasObs,
        liderGrupoObs,
        profesionTieneObs,
        experienciaFracsObs,
        nombreEspecialistaObs,
        experticeEspecialistaObs,
        informacionAnalisisPozoObs,
        areasInfoObs,
        analizaInfObs,
        criteriosPozoFracObs,
        comoPozoReqFracObs,
        estimanDanioObs,
        identificanDanioObs,
        quienMuestrasPozoObs,
        laboratorioPemexObs,
        quienProgrLabObs,
        quienSuprvLabObs,
        informeResPemex,
        informeResPemexObs,
        seleccionCIAObs,
        pruebasQuimicosObs,
        pruebasSolubilidad,
        pruebasSolubilidadObs,
        compatibilidadEmulsion,
        compatibilidadEmulsionObs,
        caractFisicoQuimicas,
        caractFisicoQuimicasObs,
        porcentajeAceite,
        porcentajeAceiteObs,
        porcentajeAgua,
        porcentajeAguaObs,
        porcentajeEmulsion,
        porcentajeEmulsionObs,
        porcentajeSolidos,
        porcentajeSolidosObs,
        porcentajeAsfaltenos,
        porcentajeAsfaltenosObs,
        porcentajeParafinas,
        porcentajeParafinasObs,
        porcentajeResinas,
        porcentajeResinasObs,
        porcentajeContSolidos,
        porcentajeContSolidosObs,
        densidadAceite,
        densidadAceiteObs,
        densidadAgua,
        densidadAguaObs,
        densidadEmulsion,
        densidadEmulsionObs,
        viscosidadAceite,
        viscosidadAceiteObs,
        viscosidadEmulsion,
        viscosidadEmulsionObs,
        phAgua,
        phAguaObs,
        salinidadAgua,
        salinidadAguaObs,
        salinidadAceite,
        salinidadAceiteObs,
        stiffDavis,
        stiffDavisObs,
        estabilidadAgua,
        estabilidadAguaObs,
        sara,
        saraObs,
        estabilidadColoidal,
        estabilidadColoidalObs,
        gravadoRoca,
        gravadoRocaObs,
        esfericidad,
        esfericidadObs,
        redondez,
        redondezObs,
        resistenciaEsfuerzo,
        resistenciaEsfuerzoObs,
        tamiz,
        tamizObs,
        aglutinamiento,
        aglutinamientoObs,
        turbidez,
        turbidezObs,
        solubilidadApunt,
        solubilidadApuntObs,
        viscosidad,
        viscosidadObs,
        hidratacionFluido,
        hidratacionFluidoObs,
        activacionGel,
        activacionGelObs,
        determinacionPhGel,
        determinacionPhGelObs,
        rompimientoGel,
        rompimientoGelObs,
        quebradores,
        quebradoresObs,
        criteriosSeleccQuimicosObs,
        criteriosSeleccGelObs,
        criteriosSeleccAcidoObs,
        labCertificacion,
        labCertificacionObs,
        dbLabs,
        dbLabsObs,
        disenioFracturasObs,
        cuentaSoftware,
        cuentaSoftwareObs,
        determinacionVolumenObs,
        yacimientoDepresionados,
        yacimientoDepresionadosObs,
        rangoTempObs,
        carbonatosArenasObs,
        beneficioFracObs,
        analisisEconomico,
        analisisEconomicoObs,
        diferentesEscenarios,
        diferentesEscenariosObs,
        baseUsuarioObs,
        quienProgFracObs,
        entregaBaseObs,
        supervisaEjecObs,
        controlCalidad,
        controlCalidadObs,
        monitoreoEjecucion,
        monitoreoEjecucionObs,
        ajustesDisenio,
        ajustesDisenioObs,
        reportePost,
        reportePostObs,
        abreProdObs,
        medicionPozoPost,
        medicionPozoPostObs,
        programaTomaMuestras,
        programaTomaMuestrasObs,
        evaluacionPostfrac,
        evaluacionPostfracObs,
        comoEvalTecnicaObs,
        variablesEcoPostObs,
        progAccionesMejopra,
        progAccionesMejopraObs
    } = req.body

    connection.query(`INSERT INTO DiagnosticoMapeo (ID, ACTIVO_ID, ASIGNACION, CUENTAN_PROCESOS_FRACT, CUENTAN_PROCESOS_FRACT_OBS, CUANTOS_SUBPROCESOS_OBS, PROCESO_PATENTADO, PROCESO_PATENTADO_OBS, ANIO_DESARROLLO_OBS, EQUIPO_TRABAJO, EQUIPO_TRABAJO_OBS, CUANTOS_ESPECIALISTAS_OBS, LIDER_GRUPO_OBS, PROFESION_TIENE_OBS, EXPERIENCIA_FRACS_OBS, NOMBRE_ESPECIALISTAS_OBS, EXPERTICE_ESPECIALISTAS_OBS, INFORMACION_ANALISIS_POZOS_OBS, AREAS_INFO_OBS, ANALIZA_INF_OBS, CRITERIOS_POZO_FRAC_OBS, COMO_POZO_REQ_FRAC_OBS, ESTIMAN_DANIO_OBS, IDENTIFICAN_DANIO_OBS, QUIEN_MUESTRAS_POZO_OBS, LABORATORIO_PEMEX, LABORATORIO_PEMEX_OBS, QUIEN_PROGR_LAB_OBS, QUIEN_SUPERV_LAB_OBS, INFORME_RES_PEMEX, INFORME_RES_PEMEX_OBS, SELECCION_CIA_OBS, PRUEBAS_QUIMICOS_OBS, PRUEBAS_SOLUBILIDAD, PRUEBAS_SOLUBILIDAD_OBS, COMPATIBILIDAD_EMULSION, COMPATIBILIDAD_EMULSION_OBS, CARACT_FISICO_QUIMICAS, CARACT_FISICO_QUIMICAS_OBS, PORCENTAJE_ACEITE, PORCENTAJE_ACEITE_OBS, PORCENTAJE_AGUA, PORCENTAJE_AGUA_OBS, PORCENTAJE_EMULSION, PORCENTAJE_EMULSION_OBS, PORCENTAJE_SOLIDOS, PORCENTAJE_SOLIDOS_OBS, PORCENTAJE_ASFALTENOS, PORCENTAJE_ASFALTENOS_OBS, PORCENTAJE_PARAFINAS, PORCENTAJE_PARAFINAS_OBS, PORCENTAJE_RESINAS, PORCENTAJE_RESINAS_OBS, PORCENTAJE_CONT_SOLIDOS, PORCENTAJE_CONT_SOLIDOS_OBS, DENSIDAD_ACEITE, DENSIDAD_ACEITE_OBS, DENSIDAD_AGUA, DENSIDAD_AGUA_OBS, DENSIDAD_EMULSION, DENSIDAD_EMULSION_OBS, VISCOSIDAD_ACEITE, VISCOSIDAD_ACEITE_OBS, VISCOSIDAD_EMULSION, VISCOSIDAD_EMULSION_OBS, PH_AGUA, PH_AGUA_OBS, SALINIDAD_AGUA, SALINIDAD_AGUA_OBS, SALINIDAD_ACEITE, SALINIDAD_ACEITE_OBS, STIFF_DAVIS, STIFF_DAVIS_OBS, ESTABILIDAD_AGUA, ESTABILIDAD_AGUA_OBS, SARA, SARA_OBS, ESTABILIDAD_COLOIDAL, ESTABILIDAD_COLOIDAL_OBS, GRAVADO_ROCA, GRAVADO_ROCA_OBS, ESFERICIDAD, ESFERICIDAD_OBS, REDONDEZ, REDONDEZ_OBS, RESISTENCIA_ESFUERZO, RESISTENCIA_ESFUERZO_OBS, TAMIZ, TAMIZ_OBS, AGLUTINAMIENTO, AGLUTINAMIENTO_OBS, TURBIDEZ, TURBIDEZ_OBS, SOLUBILIDAD_APUNT, SOLUBILIDAD_APUNT_OBS, VISCOSIDAD_GEL_FRAC, VISCOSIDAD_GEL_FRAC_OBS, HIDRATACION_FLUIDO, HIDRATACION_FLUIDO_OBS, ACTIVACION_GEL, ACTIVACION_GEL_OBS, DETERMINACION_PH_GEL, DETERMINACION_PH_GEL_OBS, ROMPIMIENTO_GEL, ROMPIMIENTO_GEL_OBS, QUEBRADORES, QUEBRADORES_OBS, CRITERIOS_SELECC_QUIMICOS_OBS, CRITERIOS_SELECC_GEL_OBS, CRITERIOS_SELECC_APUNT_OBS, LAB_CERTIFICACION, LAB_CERTIFICACION_OBS, BD_LABS, BD_LABS_OBS, DISENIO_FRACTURAS_OBS, CUENTA_SOFTWARE, CUENTA_SOFTWARE_OBS, DETERMINACION_VOLUMENES_OBS, YACIMIENTOS_DEPRESIONADOS, YACIMIENTOS_DEPRESIONADOS_OBS, RANGO_TEMP_OBS, CARBONATOS_ARENAS_OBS, BENEFICIO_FRAC_OBS, ANALISIS_ECONOMICO, ANALISIS_ECONOMICO_OBS, DIFERENTES_ESCENARIOS, DIFERENTES_ESCENARIOS_OBS, BASE_USUARIO_OBS, QUIEN_PROG_FRAC_OBS, ENTREGA_BASE_OBS, SUPERVISA_EJEC_OBS, CONTROL_CALIDAD, CONTROL_CALIDAD_OBS, MONITOREO_EJECUCION, MONITOREO_EJECUCION_OBS, AJUSTES_DISENIO, AJUSTES_DISENIO_OBS, REPORTE_POST, REPORTE_POST_OBS, ABRE_PROD_OBS, MEDICION_POZO_POST, MEDICION_POZO_POST_OBS, PROGRAMA_TOMA_MUESTRAS, PROGRAMA_TOMA_MUESTRAS_OBS, EVALUACION_POSTFRAC, EVALUACION_POSTFRAC_OBS, COMO_EVAL_TECNICA_OBS, VARIABLES_ECO_POST_OBS, PROG_ACCIONES_MEJOPRA, PROG_ACCIONES_MEJOPRA_OBS) VALUES (null, ?, ?, b?, ?, ?, b?, ?, ?, b?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, b?, ?, ?, ?, b?, ?, b?, ?, b?, ?, b?, ?, b?, ?, b?, ?, b?, ?, b?, ?, b?, ?, b?, ?, b?, ?, b?, ?, b?, ?, b?, ?, b?, ?, b?, ?, b?, ?, b?, ?, b?, ?, b?, ?, b?, ?, b?, ?, b?, ?, b?, ?, b?, ?, b?, ?, b?, ?, b?, ?, b?, ?, b?, ?, b?, b?, b?, ?, b?, ?, b?, ?, b?, ?, b?, ?, b?, ?, ?, ?, ?, b?, ?, b?, ?, ?, b?, ?, ?, b?, ?, ?, ?, ?, b?, ?, b?, ?, ?, ?, ?, ?, b?, ?, b?, ?, b?, ?, b?, ?, ?, b?, ?, b?, ?, b?, ?, ?, ?, b?, ? )`,
        [ activo,
            asignacion,
            cuentanProcesos,
            cuentanProcesosObs,
            cuantosProcesosObs,
            procesoPatentado,
            procesoPatentadoObs,
            anioDesarrolloObs,
            equipoTrabajo,
            equipoTrabajoObs,
            cuantosEspecialistasObs,
            liderGrupoObs,
            profesionTieneObs,
            experienciaFracsObs,
            nombreEspecialistaObs,
            experticeEspecialistaObs,
            informacionAnalisisPozoObs,
            areasInfoObs,
            analizaInfObs,
            criteriosPozoFracObs,
            comoPozoReqFracObs,
            estimanDanioObs,
            identificanDanioObs,
            quienMuestrasPozoObs,
            laboratorioPemexObs,
            quienProgrLabObs,
            quienSuprvLabObs,
            informeResPemex,
            informeResPemexObs,
            seleccionCIAObs,
            pruebasQuimicosObs,
            pruebasSolubilidad,
            pruebasSolubilidadObs,
            compatibilidadEmulsion,
            compatibilidadEmulsionObs,
            caractFisicoQuimicas,
            caractFisicoQuimicasObs,
            porcentajeAceite,
            porcentajeAceiteObs,
            porcentajeAgua,
            porcentajeAguaObs,
            porcentajeEmulsion,
            porcentajeEmulsionObs,
            porcentajeSolidos,
            porcentajeSolidosObs,
            porcentajeAsfaltenos,
            porcentajeAsfaltenosObs,
            porcentajeParafinas,
            porcentajeParafinasObs,
            porcentajeResinas,
            porcentajeResinasObs,
            porcentajeContSolidos,
            porcentajeContSolidosObs,
            densidadAceite,
            densidadAceiteObs,
            densidadAgua,
            densidadAguaObs,
            densidadEmulsion,
            densidadEmulsionObs,
            viscosidadAceite,
            viscosidadAceiteObs,
            viscosidadEmulsion,
            viscosidadEmulsionObs,
            phAgua,
            phAguaObs,
            salinidadAgua,
            salinidadAguaObs,
            salinidadAceite,
            salinidadAceiteObs,
            stiffDavis,
            stiffDavisObs,
            estabilidadAgua,
            estabilidadAguaObs,
            sara,
            saraObs,
            estabilidadColoidal,
            estabilidadColoidalObs,
            gravadoRoca,
            gravadoRocaObs,
            esfericidad,
            esfericidadObs,
            redondez,
            redondezObs,
            resistenciaEsfuerzo,
            resistenciaEsfuerzoObs,
            tamiz,
            tamizObs,
            aglutinamiento,
            aglutinamientoObs,
            turbidez,
            turbidezObs,
            solubilidadApunt,
            solubilidadApuntObs,
            viscosidad,
            viscosidadObs,
            hidratacionFluido,
            hidratacionFluidoObs,
            activacionGel,
            activacionGelObs,
            determinacionPhGel,
            determinacionPhGelObs,
            rompimientoGel,
            rompimientoGelObs,
            quebradores,
            quebradoresObs,
            criteriosSeleccQuimicosObs,
            criteriosSeleccGelObs,
            criteriosSeleccAcidoObs,
            labCertificacion,
            labCertificacionObs,
            dbLabs,
            dbLabsObs,
            disenioFracturasObs,
            cuentaSoftware,
            cuentaSoftwareObs,
            determinacionVolumenObs,
            yacimientoDepresionados,
            yacimientoDepresionadosObs,
            rangoTempObs,
            carbonatosArenasObs,
            beneficioFracObs,
            analisisEconomico,
            analisisEconomicoObs,
            diferentesEscenarios,
            diferentesEscenariosObs,
            baseUsuarioObs,
            quienProgFracObs,
            entregaBaseObs,
            supervisaEjecObs,
            controlCalidad,
            controlCalidadObs,
            monitoreoEjecucion,
            monitoreoEjecucionObs,
            ajustesDisenio,
            ajustesDisenioObs,
            reportePost,
            reportePostObs,
            abreProdObs,
            medicionPozoPost,
            medicionPozoPostObs,
            programaTomaMuestras,
            programaTomaMuestrasObs,
            evaluacionPostfrac,
            evaluacionPostfracObs,
            comoEvalTecnicaObs,
            variablesEcoPostObs,
            progAccionesMejopra,
            progAccionesMejopraObs
        ], (err, results) => {
            console.log('mapeo err', err)
            console.log('mapeo', results)
            if (err) {
                res.json({ success: false})
            }
            else {
                res.json({ success: true})
            }
        })
}

export const get = function(req, res) {
    let id = req.params.id

    connection.query(`SELECT 
        ID, 
        ACTIVO_ID as activo,
        ASIGNACION as asignacion,
        CUENTAN_PROCESOS_FRACT as cuentanProcesos,
        CUENTAN_PROCESOS_FRACT_OBS as cuentanProcesosObs,
        CUANTOS_SUBPROCESOS_OBS as cuantosProcesosObs,
        PROCESO_PATENTADO as procesoPatentado,
        PROCESO_PATENTADO_OBS as procesoPatentadoObs,
        ANIO_DESARROLLO_OBS as anioDesarrolloObs,
        EQUIPO_TRABAJO as equipoTrabajo,
        EQUIPO_TRABAJO_OBS as equipoTrabajoObs,
        CUANTOS_ESPECIALISTAS_OBS as cuantosEspecialistasObs,
        LIDER_GRUPO_OBS as liderGrupoObs,
        PROFESION_TIENE_OBS as profesionTieneObs,
        EXPERIENCIA_FRACS_OBS as experienciaFracsObs,
        NOMBRE_ESPECIALISTAS_OBS as nombreEspecialistaObs,
        EXPERTICE_ESPECIALISTAS_OBS as experticeEspecialistaObs,
        INFORMACION_ANALISIS_POZOS_OBS as informacionAnalisisPozoObs,
        AREAS_INFO_OBS as areasInfoObs,
        ANALIZA_INF_OBS as analizaInfObs,
        CRITERIOS_POZO_FRAC_OBS as criteriosPozoFracObs,
        COMO_POZO_REQ_FRAC_OBS as comoPozoReqFracObs,
        ESTIMAN_DANIO_OBS as estimanDanioObs,
        IDENTIFICAN_DANIO_OBS as identificanDanioObs,
        QUIEN_MUESTRAS_POZO_OBS as quienMuestrasPozoObs,
        LABORATORIO_PEMEX as laboratorioPemex,
        LABORATORIO_PEMEX_OBS as laboratorioPemexObs,
        QUIEN_PROGR_LAB_OBS as quienProgrLabObs,
        QUIEN_SUPERV_LAB_OBS as quienSuprvLabObs,
        INFORME_RES_PEMEX as quienSuprvLabObs,
        INFORME_RES_PEMEX_OBS as informeResPemexObs,
        SELECCION_CIA_OBS as seleccionCIAObs,
        PRUEBAS_QUIMICOS_OBS as pruebasQuimicosObs,
        PRUEBAS_SOLUBILIDAD as pruebasSolubilidad,
        PRUEBAS_SOLUBILIDAD_OBS as pruebasSolubilidadObs,
        COMPATIBILIDAD_EMULSION as compatibilidadEmulsion,
        COMPATIBILIDAD_EMULSION_OBS as compatibilidadEmulsionObs,
        CARACT_FISICO_QUIMICAS as caractFisicoQuimicas,
        CARACT_FISICO_QUIMICAS_OBS as caractFisicoQuimicasObs,
        PORCENTAJE_ACEITE as porcentajeAceite,
        PORCENTAJE_ACEITE_OBS as porcentajeAceiteObs,
        PORCENTAJE_AGUA as porcentajeAgua,
        PORCENTAJE_AGUA_OBS as porcentajeAguaObs,
        PORCENTAJE_EMULSION as porcentajeEmulsion,
        PORCENTAJE_EMULSION_OBS as porcentajeEmulsionObs,
        PORCENTAJE_SOLIDOS as porcentajeSolidos,
        PORCENTAJE_SOLIDOS_OBS as porcentajeSolidosObs,
        PORCENTAJE_ASFALTENOS as porcentajeAsfaltenos,
        PORCENTAJE_ASFALTENOS_OBS as porcentajeAsfaltenosObs,
        PORCENTAJE_PARAFINAS as porcentajeParafinas,
        PORCENTAJE_PARAFINAS_OBS as porcentajeParafinasObs,
        PORCENTAJE_RESINAS as porcentajeResinas,
        PORCENTAJE_RESINAS_OBS as porcentajeResinasObs,
        PORCENTAJE_CONT_SOLIDOS as porcentajeContSolidos,
        PORCENTAJE_CONT_SOLIDOS_OBS as porcentajeContSolidosObs,
        DENSIDAD_ACEITE as densidadAceite,
        DENSIDAD_ACEITE_OBS as densidadAceiteObs,
        DENSIDAD_AGUA as densidadAgua,
        DENSIDAD_AGUA_OBS as densidadAguaObs,
        DENSIDAD_EMULSION as densidadEmulsion,
        DENSIDAD_EMULSION_OBS as densidadEmulsionObs,
        VISCOSIDAD_ACEITE as viscosidadAceite,
        VISCOSIDAD_ACEITE_OBS as viscosidadAceiteObs,
        VISCOSIDAD_EMULSION as viscosidadEmulsion,
        VISCOSIDAD_EMULSION_OBS as viscosidadEmulsionObs,
        PH_AGUA as phAgua,
        PH_AGUA_OBS as phAguaObs,
        SALINIDAD_AGUA as salinidadAgua,
        SALINIDAD_AGUA_OBS as salinidadAguaObs,
        SALINIDAD_ACEITE as salinidadAceite,
        SALINIDAD_ACEITE_OBS as salinidadAceiteObs,
        STIFF_DAVIS as stiffDavis,
        STIFF_DAVIS_OBS as stiffDavisObs,
        ESTABILIDAD_AGUA as estabilidadAgua,
        ESTABILIDAD_AGUA_OBS as estabilidadAguaObs,
        SARA as sara,
        SARA_OBS as saraObs,
        ESTABILIDAD_COLOIDAL as estabilidadColoidal,
        ESTABILIDAD_COLOIDAL_OBS as estabilidadColoidalObs,
        GRAVADO_ROCA as gravadoRoca,
        GRAVADO_ROCA_OBS as gravadoRocaObs,
        ESFERICIDAD as esfericidad,
        ESFERICIDAD_OBS as esfericidadObs,
        REDONDEZ as redondez,
        REDONDEZ_OBS as redondezObs,
        RESISTENCIA_ESFUERZO as resistenciaEsfuerzo,
        RESISTENCIA_ESFUERZO_OBS as resistenciaEsfuerzoObs,
        TAMIZ as tamiz,
        TAMIZ_OBS as tamizObs,
        AGLUTINAMIENTO as aglutinamiento,
        AGLUTINAMIENTO_OBS as aglutinamientoObs,
        TURBIDEZ as turbidez,
        TURBIDEZ_OBS as turbidezObs,
        SOLUBILIDAD_APUNT as solubilidadApunt,
        SOLUBILIDAD_APUNT_OBS as solubilidadApuntObs,
        VISCOSIDAD_GEL_FRAC as viscosidad,
        VISCOSIDAD_GEL_FRAC_OBS as viscosidadObs,
        HIDRATACION_FLUIDO as hidratacionFluido,
        HIDRATACION_FLUIDO_OBS as hidratacionFluidoObs,
        ACTIVACION_GEL as activacionGel,
        ACTIVACION_GEL_OBS as activacionGelObs,
        DETERMINACION_PH_GEL as determinacionPhGel,
        DETERMINACION_PH_GEL_OBS as determinacionPhGelObs,
        ROMPIMIENTO_GEL as rompimientoGel,
        ROMPIMIENTO_GEL_OBS as rompimientoGelObs,
        QUEBRADORES as quebradores,
        QUEBRADORES_OBS as quebradoresObs,
        CRITERIOS_SELECC_QUIMICOS_OBS as criteriosSeleccQuimicosObs,
        CRITERIOS_SELECC_GEL_OBS as criteriosSeleccGelObs,
        CRITERIOS_SELECC_APUNT_OBS as criteriosSeleccAcidoObs,
        LAB_CERTIFICACION as labCertificacion,
        LAB_CERTIFICACION_OBS as labCertificacionObs,
        BD_LABS as dbLabs,
        BD_LABS_OBS as dbLabsObs,
        DISENIO_FRACTURAS_OBS as disenioFracturasObs,
        CUENTA_SOFTWARE as cuentaSoftware,
        CUENTA_SOFTWARE_OBS as cuentaSoftwareObs,
        DETERMINACION_VOLUMENES_OBS as determinacionVolumenObs,
        YACIMIENTOS_DEPRESIONADOS as yacimientoDepresionados,
        YACIMIENTOS_DEPRESIONADOS_OBS as yacimientoDepresionadosObs,
        RANGO_TEMP_OBS as rangoTempObs,
        CARBONATOS_ARENAS_OBS as carbonatosArenasObs,
        BENEFICIO_FRAC_OBS as beneficioFracObs,
        ANALISIS_ECONOMICO as analisisEconomico,
        ANALISIS_ECONOMICO_OBS as analisisEconomicoObs,
        DIFERENTES_ESCENARIOS as diferentesEscenarios,
        DIFERENTES_ESCENARIOS_OBS as diferentesEscenariosObs,
        BASE_USUARIO_OBS as baseUsuarioObs,
        QUIEN_PROG_FRAC_OBS as quienProgFracObs,
        ENTREGA_BASE_OBS as entregaBaseObs,
        SUPERVISA_EJEC_OBS as supervisaEjecObs,
        CONTROL_CALIDAD as controlCalidad,
        CONTROL_CALIDAD_OBS as controlCalidadObs,
        MONITOREO_EJECUCION as monitoreoEjecucion,
        MONITOREO_EJECUCION_OBS as monitoreoEjecucionObs,
        AJUSTES_DISENIO as ajustesDisenio,
        AJUSTES_DISENIO_OBS as ajustesDisenioObs,
        REPORTE_POST as reportePost,
        REPORTE_POST_OBS as reportePostObs,
        ABRE_PROD_OBS as abreProdObs,
        MEDICION_POZO_POST as medicionPozoPost,
        MEDICION_POZO_POST_OBS as medicionPozoPostObs,
        PROGRAMA_TOMA_MUESTRAS as programaTomaMuestras,
        PROGRAMA_TOMA_MUESTRAS_OBS as programaTomaMuestrasObs,
        EVALUACION_POSTFRAC as evaluacionPostfrac,
        EVALUACION_POSTFRAC_OBS as evaluacionPostfracObs,
        COMO_EVAL_TECNICA_OBS as comoEvalTecnicaObs,
        VARIABLES_ECO_POST_OBS as variablesEcoPostObs,
        PROG_ACCIONES_MEJOPRA as progAccionesMejopra,
        PROG_ACCIONES_MEJOPRA_OBS as progAccionesMejopraObs
    FROM DiagnosticoMapeo 
    WHERE ID = ? `, [id] , (err, results) => {
        console.log('mapeo err', err)
        console.log('mapeo', results)
        res.json(results)
    })
}

export const getAll = function(req, res) {
    connection.query(`SELECT 
        ID, 
        ACTIVO_ID as activo, 
        ASIGNACION as asignacion 
      FROM DiagnosticoMapeo`, (err, results) => {
        console.log('mapeo err', err)
        console.log('mapeo', results)
        res.json(results)
    })
}
