export const setSubdireccion = value => ({ type: 'set_subdireccion', value})
export const setBloque = value => ({ type: 'set_bloque', value})
export const setActivo = value => ({ type: 'set_activo', value})
export const setCampo = value => ({ type: 'set_campo', value})
export const setPozo = value => ({ type: 'set_pozo', value})
export const setFormacion = value => ({ type: 'set_formacion', value})