const units = {
  pressure: 'Kg/cm2',
  pressureEnglish: 'psi',
  densityApi: '°API',
  density: 'gr/cm3',
  pressurePerYear: 'Kg/cm2/año',
  pressurePerMonth: 'Kg/cm2/mes',
  measuredDepth: 'md',
  verticalDepth: 'mv',
  depthUnderSeaLevel: 'mvbnm',
  rga: 'm3/m3',
  ppm: 'ppm',
  length: 'm',
  percent: '%',
  barrelsPerDay: 'bpd',
  cubicFeetPerDay: 'MMpcd',
  billionBarrels: 'MMb',
  trillionCubicFeetPerDay: 'MMMpc',
  temperature: '°C',
  viscosity: 'cp',
  specificGravity: 'Adim.',
  milliDarcy: 'mD',
  kh: 'mD*ft',
  unidades: 'unidades',
  pulgadas: 'pg',
  degreesText: 'Grados',
  disparosDensity: 'c/m',
  volume: 'm3',
}

const field = {
  generales: {
    descubrimientoField: { text: 'Descubrimiento', unit: '' },
    fechaDeExplotacionField: { text: 'Fecha de explotación', unit: '' },
    numeroDePozosOperandoField: { text: 'No. de pozos operando', unit: '' },
  },
  explotacion: {
    pActualFechaField: { text: 'Fecha de presión actual', unit: '' },
    pActualField: { text: 'Presión actual', unit: units.pressure },
    pInicialAnoField: { text: 'Fecha de presión inicial', unit: '' },
    pInicialField: { text: 'Presión inicial', unit: units.pressure },
    dpPerAnoField: { text: 'DP/año', unit: units.pressurePerYear },
    tyacField: { text: 'T yac', unit: units.temperature },
    prField: { text: 'Profundidad al Plano de Referencia', unit: units.depthUnderSeaLevel },
  },
  fluido: {
    tipoDeFluidoField: { text: 'Tipo de Fluido', unit: '' },
    densidadDelAceiteField: { text: 'Densidad del aceite', unit: units.densityApi },
    pSatField: { text: 'Presión de saturación', unit: units.pressure },
    rgaFluidoField: { text: 'RGA', unit: units.rga },
    salinidadField: { text: 'Salinidad', unit: units.ppm },
    pvtRepresentativoField: { text: 'PVT representativo', unit: '' },
  },
  formacion: {
    litologiaField: { text: 'Litología', unit: '' },
    espesorNetoField: { text: 'Espesor neto', unit: units.length },
    porosidadField: { text: 'Porosidad', unit: units.percent },
    swField: { text: 'Sw', unit: units.percent },
    kPromedioField: { text: 'K promedio', unit: units.milliDarcy },
    caaField: { text: 'CAA', unit: units.length },
    cgaField: { text: 'CGA', unit: units.length },
  },
  produccion: {
    qoField: { text: 'Qo', unit: units.barrelsPerDay },
    qgField: { text: 'Qg', unit: units.cubicFeetPerDay },
    rgaField: { text: 'RGA', unit: units.rga },
    fwField: { text: 'Fw', unit: units.percent },
    npField: { text: 'Np', unit: units.billionBarrels },
    gpField: { text: 'Gp', unit: units.trillionCubicFeetPerDay },
    wpField: { text: 'Wp', unit: units.billionBarrels },
    rraField: { text: 'RRA', unit: units.billionBarrels },
    rrgField: { text: 'RRG', unit: units.trillionCubicFeetPerDay },
    rrpceField: { text: 'RRPCE', unit: units.billionBarrels },
    h2sField: { text: 'H2S', unit: units.percent },
    co2Field: { text: 'CO2', unit: units.percent },
    n2Field: { text: 'N2', unit: units.percent },
  },
}

const well = {
  datos: {
    tipoDePozo: { text: 'Tipo de pozo', unit: '' },
    pws: { text: 'Pws', unit: units.pressure },
    pwsFecha: { text: 'Pws (fecha)', unit: '' },
    pwf: { text: 'Pwf', unit: units.pressure },
    pwfFecha: { text: 'Pwf (fecha)', unit: '' },
    deltaPPerMes: { text: 'Δp/mes', unit: units.pressurePerMonth },
    tyac: { text: 'Tyac', unit: units.temperature },
    pvt: { text: 'PVT', unit: '' },
    pvtaparejoDeProduccion: { text: 'Aparejo de producción', unit: '' },
    profEmpacador: { text: 'Profundidad empacador', unit: units.measuredDepth },
    profSensorPYT: { text: 'Profundidad sensor P y T', unit: units.measuredDepth },
  },
  fluido: {
    densidadAceite: { text:'Densidad del aceite', unit: units.densityApi },
    bo: { text:'Bo', unit: units.rga },
    viscosidadAceite: { text:'Viscosidad del aceite', unit: units.viscosity },
    gravedadEspecificaGas: { text:'Gravedad específica del gas', unit: 'Adim.' },
    bg: { text:'Bg', unit: units.rga},
    rga: { text:'RGA', unit: units.rga },
    asfaltenos: { text:'RGA', unit: units.percent },
    parafinas: { text:'Parafinas', unit: units.percent },
    resinasAsfalticas: { text:'Resinas asfalticas', unit: units.percent },
    indiceEstColoidal: { text:'Índice de est. coloidal', unit: units.specificGravity },
    densidadAgua: { text:'Densidad del agua', unit: units.density },
    contenidoAgua: { text:'Contenido de agua', unit: units.percent },
    salinidad: { text:'Salinidad', unit: units.ppm },
    ph: { text:'pH', unit: '' },
    indiceEstAgua: { text:'Índice de est. del agua', unit: units.specificGravity },
    contenidoEmulsion: { text:'Contenido de emulsión', unit: units.percent },
  },
  formacion: {
    caliza: { text: 'Caliza', unit: units.percent },
    dolomia: { text: 'Dolomia', unit: units.percent },
    arcilla: { text: 'Arcilla', unit: units.percent },
    porosidad: { text: 'Porosidad', unit: units.percent },
    permeabilidad: { text: 'Permeabilidad', unit: units.milliDarcy },
    sw: { text: 'Sw', unit: units.percent },
    caa: { text: 'CAA', unit: units.depthUnderSeaLevel },
    cga: { text: 'CGA', unit: units.depthUnderSeaLevel },
  },
  presion: {
    pruebaDePresion: { text: "Prueba de presión", unit: '' },
    modelo: { text: "Modelo", unit: '' },
    kh: { text: "Kh", unit: units.kh },
    k: { text: "K", unit: units.milliDarcy },
    s: { text: "S", unit: units.unidades },
    piEnNivelSonda: { text: "Pi @ nivel sonda", unit: units.pressure } ,
  },
}

const estadoMecanicoYAparejo = {
  terminacion: {
    tipoDeTerminacion: { text: 'Tipo de terminación', unit: '' },
    hIntervaloProductor: { text: 'h (intervalo productor)', unit: units.verticalDepth },
    empacador: { text: 'Empacador', unit: units.verticalDepth },
    presionDifEmpacador: { text: 'Presión dif. empacador', unit: units.pressureEnglish },
    sensorPyt: { text: 'Profundidad Sensor P y T', unit: units.verticalDepth },
  },
  liner: {
    tipoDeLiner: { text: "Tipo de liner", unit: '', },
    diametroDeLiner: { text: "Diámetro de liner", unit: units.pulgadas },
  },
  disparos: {
    tipoDePistolas: { text: 'Tipo de pistolas', unit: '' },
    densidadDeDisparosMecanico: { text: 'Densidad de disparos', unit: units.disparosDensity },
    fase: { text: 'Fase', unit: units.degreesText },
    diametroDeOrificio: { text: 'Diámetro de orificio', unit: units.pulgadas },
    penetracion: { text: 'Penetración', unit: units.pulgadas, },
  },
  volumen: {
    tratamientoPor: { text: 'Tratamiento Por', unit: '' },
    volumenAparejoDeProduccion: { text: "Volumen aparejo de producción", unit: units.volume },
    volumenCimaDeIntervalo: { text: "Volumen @ cima de intervalo", unit: units.volume },
    volumenBaseDeIntervalo: { text: "Volumen @ base de intervalo", unit: units.volume },
    volumenDeEspacioAnular: { text: "Volumen de espacio anular (EA)", unit: units.volume },
  }
}

export const maps = {
  field,
  well,
  estadoMecanicoYAparejo,
}
